title: Etimologías
description: Etimologías Grecolatinas del Español · Escuela de Bachilleres UAQ
remote_theme: just-the-docs/just-the-docs
lang: es

plugins:
  - jekyll-remote-theme

search_enabled: true
search:
  heading_level: 3
  button: true

aux_links:
  "DLE (RAE)":
    - "https://dle.rae.es"
  "DECEL":
    - "http://etimologias.dechile.net"

heading_anchors: true
color_scheme: etimologias

callouts:
  reto:
    title: Reto
    color: purple
  ojo:
    title: Ojo
    color: yellow

footer_content: "Etimologías Grecolatinas del Español · Escuela de Bachilleres · UAQ"
